version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ss060900
    ports:
      - 3306:3306
  lab6-app:
    restart: on-failure
    build: ./
    expose:
      - "8888"
    ports:
      - 8888:8888
    depends_on:
      - docker-mysql

volumes:
  db-data:
